### ISSUE TITLE
PSX Autosplitter doesn't split on Shaft

### ISSUE THREAD

**Issue by DerDrach** [TalicZealot/SotN-Autosplitters#1]
While using this for Richter runs on Bizhawk it will not split when defeating Shaft when Shaft on = true. 
In my testing I found this is due to (location.mapY.current + location.mapYoffset.current) returning 32 in Shafts boss arena when the code is checking for it to be 34 on Shafts defeat to split. When I changed it to check for the value 32 it would split properly when defeating Shaft.
I tested this with Alucard after just to make sure and it is the same case there.

**Comment by TalicZealot** [comment]
You're completely right, thank you for reporting the issue! Resolved in https://github.com/TalicZealot/SotN-Autosplitters/commit/869d991ee730648fa9bff9499ae645bd7136b3a3
